### ISSUE TITLE
Missing device as input in the non LSTM models.

### ISSUE THREAD

**Issue by LittlePea13** [AndriyMulyar/bert_document_classification#1]
The forward passes for the non-LSTM based architectures are missing the device input which is given when called in the document_bert script, leading to an error.

It is fixed by just adding it as in the LSTM one,
`def forward(self, document_batch: torch.Tensor, document_sequence_lengths: list, freeze_bert=False, device='cuda'):
`
In lines 72 and 117 in the document_bert_architectures file.

(I can add it as pull request but assumed you would rather fix it yourself)
PS: Thanks for your work!

**Comment by AndriyMulyar** [comment]
Thank you! Will get around to this as it will cause issues on multi-gpu
machines.

**Comment by AndriyMulyar** [comment]
done
