### ISSUE TITLE
correct bug in the code too?

### ISSUE THREAD

**Issue by vr25** [AndriyMulyar/bert_document_classification#13]
Hi,

The paper correction (https://arxiv.org/pdf/1910.13664.pdf) identifies a bug and so I was wondering if it'd be corrected in the code too? Also, what was the bug in the implementation?

Thanks!

**Comment by AndriyMulyar** [comment]
Yes the code it corrected! However, the performance numbers in the main
README are not accurate. See the preprint for

**Comment by vr25** [comment]
Alright, thanks for your quick reply.
