### ISSUE TITLE
AssertionError: Your document is to large, arbitrary size when writing

### ISSUE THREAD

**Issue by zeinramadan** [AndriyMulyar/bert_document_classification#22]
What is the meaning of this error? I thought this architecture was designed to handle long documents?

**Comment by zeinramadan** [comment]
Is there a limit to the size of the documents that can be fed into the model?

**Comment by AndriyMulyar** [comment]
7x512

**Comment by zeinramadan** [comment]
ah ok perfect thanks for clearing that up! I'll filter out any documents longer than that.
